name = "DielectricRaster"
uuid = "98ea7f3b-57b7-44f3-9d4a-bbb77889c19e"
authors = ["Pawel Latawiec <pawel@metalenz.com>", "Sam Buercklin <sam@metalenz.com>"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
